### PR TITLE
Improve the generated website structure

### PR DESCRIPTION
**Pull request by jonasmalacofilho**
main objectives:

 - [x] hide `.html` extensions
 - [x] improve (if possible) the readability of the url, while still keeping its desired properties: stability, seo friendliness

other features:

 - [x] normalize URIs across the board (table of contents, breadcrumbs and other links)

configuration:

 - ~better tune the cache control headers to avoid refreshes on fragment changes~ (can't reproduce)
 - [x] set-up nginx to the new behavior (`try_files $uri $uri.html`)
 - ~don't forget to set up redirection rules from old to new urls (on both servers)~ (should work, can't force redirection without breaking all other branches)

documentation:

 - [x] document the necessary development tools (`http-server --ext html`)
 - [x] document the necessary nginx settings (`try_files $uri $uri.html`)

checks:

 - [x] check that we're not breaking IE/Edge

### CODE REVIEW

**Comment by jonasmalacofilho** [comment]
This makes testing locally a bit harder, since there doesn't seem to be any option, either on Chrome or Firefox, to _automatically_ use `index.html` as a _local_ directory index, which in turn is the expected behaviour or most webserver configurations.

However, since we're already using Node.js (and npm), it's fairly easy to mitigate this (without difficult to configure or install dependencies).  Install [`http-server`](https://github.com/indexzero/http-server) (`npm install --global http-server`) and easily serve the generated directories with `http-server <path to generated dir>/html`.

**Comment by jonasmalacofilho** [comment]
@aszasz and @craice,

 - do you see any more improvements we can make to the generated file structure?
 - can you try this, both on the server and locally and give me some feedback?

**Comment by craice** [comment]
Some kind of shortcut like `brtguide.itdp.org/32.2.1`?

**Comment by craice** [comment]
`#nav-options`  opens the page again.

Edit: All the anchors open the page again.

**Comment by jonasmalacofilho** [comment]
@craice:

 - interesting, but what do you mean by making all anchors open the _page_ again?
 - not sure about `brtguide.itdp.org/32.2.1`... numbers should change more than names (which means that URLs would break more often), and bad for SEO

**Comment by aszasz** [comment]
I can hardly follow... I see it is more elegant... but I don't feel more comfortable reading url.
Uniformity is always good, and nothing else occurs to me.

**Comment by jonasmalacofilho** [comment]
@craice, @aszasz: I guess the common base is "can we improve the readability of the url, while still keeping the desired properties?"... added to the list

**Comment by craice** [comment]
When you click on the link for the subsection in the nav bar, instead of going to the anchor in the same page, it loads the page again.

**Comment by jonasmalacofilho** [comment]
@craice, thanks for reminding me about that!  It's something i caused when tuning the cache control headers...

**Comment by jonasmalacofilho** [comment]
@craice and @caio, have you tried to test branch _locally_?  I'm interested in your feedback on how it is to work and test the guide (on Windows) with the new structure and links (check the [second](https://github.com/ITDP/the-online-brt-planning-guide/pull/119#issuecomment-277651602) message if you run into too many issues).

**Comment by aszasz** [comment]
[EDIT: had not read the *second* message... I did not find annoyng to navigate by clicking in index.html for the local compilation. That is certainly not a restriction if the result pleases you... still why not add index.html via js when it reads ``file:///`` ?]
Test on Windows:
- served:  it works on FireFox Chrome and Edge and does not in IE (as expected).
- locally: 
   - it does not load the navigator in IE
   - it does not load the navigator in Edge
> XMLHttpRequest: Erro de Rede 0x800c0015, O recurso solicitado é um diretório, não um arquivo.

``document.baseURI = "file:///C:/Users/silvi/Desktop/obrt/html/"`` all right... did not check myUrl, but I guess the following shall clear it for you

-
  - it does not automatically opens the index in Firefox or Chrome 
*Now that I checked... This is the same behaviour in Linux*

**Comment by jonasmalacofilho** [comment]
@aszasz, i'll check the issue with locally running + ie.  Thanks for reporting!

In the mean time, can you see my  [second](https://github.com/ITDP/the-online-brt-planning-guide/pull/119#issuecomment-277651602) message here?  Let me know what works best (opening the the html file by hand or using the local server)?

EDIT: adding `/index.html` to all links before any click, while possible, wouldn't allow us to test the system as it will be used by the user (the user would only interact with `/` urls, but locally we would only test – on Windows – with `/index.html` urls)

**Comment by jonasmalacofilho** [comment]
I managed to reproduce the issue.  And, wow!  Just wow!  _(check the address bar and the URLs on the console)_

screenshot from 2017-02-08 00-43-57

Anyway... Fixed in Edge with (more) normalization.  IE is broken still because we're lacking #117, and because it would be a bit more annoying to fix it there (because the URLs are still different, but in a different way... wow, just wow).

Also, this happens with the 'master' branch as well.  We really need the (other) planned fix for #116, in addition to the improvements in this PR (normalization).

---

Back to a different subject...

IE and Edge, unlike Firefox and Chrome, open a file browser window when navigating to a directory.  Thus, it's ~impossible~ very impractical to navigate _locally_ (urls that start with `file://`) in those browsers with the new structure, unless there's a local server running.

This alone would be a strong argument against the new structure.  On the other hand, I just realised that we'll probably need a local server to test it anyway: the author/god mode will require async requests to the file system, and that's not something with can do on the local filesystem (disallowed on browsers because of security considerations).  _(there's still a hack I can try, but it's unlikely that it will work...)_

**Pull request merged**
