### PR TITLE
Support vertical elements in quotation text [manu]

### PR DESCRIPTION
**Pull request by jonasmalacofilho**
To do:

 - [x] change the AST from `Quotation(HElem,HElem)` to `Quotation(VElem,HElem)`:
 - [x] propagate this through structuring and validation
 - [x] implement simplified HTML generation (paragraphs only)
 - [x] update the TeX generation
 - [x] update the stylesheet for the guide
 - [ ] update the TeX preamble used by the guide
 - [ ] implement complete HTML generation of the new AST, adding support for the
       remaining (restricted mode) vertical elements

### CODE REVIEW

**Comment by jonasmalacofilho** [comment]
@aszasz can you test this and see how it works in practice?

Support for reproducing (restricted) vertical content is a desirable feature, I think, but I'm not sure about pushing all of this into the `\quotation` command.  Maybe we should differentiate between quotations and citations?

Also, citations can be used for many different purposes and, in some cases, could just as well (if not better) be handled by footnotes.

**Comment by jonasmalacofilho** [comment]
Ops, I broke TeX : \

But it looks like an easy fix...

**Comment by aszasz** [comment]
Here are the test results:
screenshot from 2017-06-16 18-24-27
screenshot from 2017-06-16 18-23-04

**Comment by aszasz** [comment]
Latex worked too... I will make a pull request to your branch , so if this get merged, Chapter 2 is using this properly.

**Comment by jonasmalacofilho** [comment]
For now, this is too incomplete to be worth merging ...

Will close and archive it for the future.

**Pull request closed without merging**
