### PR TITLE
Add raw chapter seven

### PR DESCRIPTION
**Pull request by aszasz**
As converted from word.

### CODE REVIEW

**Review by jonasmalacofilho — CHANGES_REQUESTED** [review]
- [ ] set `.emf` files to use LFS in `.gitattributes`
- [ ] remove/convert `.emf` files

**Comment by aszasz** [comment]
I can  not do it untill Tuesday, sorry!

**Comment by jonasmalacofilho** [comment]
The history of this needs to be rewritten (ideally when otherwise ready for the merge) to remove any EMF/GIF files from the non-LFS history; see #24 for an example of how to do this (or ask my help, when the time comes).

**Comment by aszasz** [comment]
Other pull request (#93) replaced this.

**Pull request closed without merging**
