### PR TITLE
Chp six

### PR DESCRIPTION
**Pull request by aszasz**
Raw files and revision until end of 6.3 completed

### CODE REVIEW

**Comment by aszasz** [comment]
Hi there, this generated the html locally... so my guess is that it has a TeX problem. Can't check until Tuesday...

**Comment by jonasmalacofilho** [comment]
> LaTeX Error: Unknown graphics extension: .emf

We don't support `.emf` files.  EMF (Enhanced Metafile) is a proprietary, non-portable and severely limited vector graphics format; in the other chapters we've been converting them to PNGs (since it's a such unsupported format that we couldn't even figure out how to convert them to SVGs).

Html is much less informative about what won't work; we're considering adding some checks to the generator (by magic numbers, not file extensions since those can easily be out of sync with the file contents), but that would also mean code changes to allow any new format, such as the new web raster graphics format or other improvements in (Xe/Lua)TeX.

**Comment by jonasmalacofilho** [comment]
Hm... Emf files are not in our `.gitattributes` filters and have _not_ been added with LFS.  Fixing that (and reading the files, with LFS) is essential before merging this!

**Review by jonasmalacofilho — CHANGES_REQUESTED** [review]
- [ ] set `.emf` files to use LFS in `.gitattributes`
- [ ] remove/convert all `.emf` files

**Comment by jonasmalacofilho** [comment]
The history of this needs to be rewritten (ideally when otherwise ready for the merge) to remove any EMF/GIF files from the non-LFS history; see #24 for an example of how to do this (or ask my help, when the time comes).

**Comment by jonasmalacofilho** [comment]
Since the merge result is [clean](https://travis-ci.org/protocubo/the-online-brt-planning-guide/builds/182277158#L145-L152) (of rogue LFS files), this can safely and simply be **squashed** and merged (even from this web ui).  : )

_This will loose the git history (GitHub will still keep it though, but it's a lot less useful), which seems ok in this case.  To keep the history, a complicated rebase would be necessary; more info on https://github.com/protocubo/the-online-brt-planning-guide/pull/24._

**Review by jonasmalacofilho — APPROVED** [review]

**Pull request merged**
