### PR TITLE
Added authors to the chapters so far

### PR DESCRIPTION
**Pull request by aegauthier**
hey y'all have no idea if this is right or wrong but here we go - let me know

### CODE REVIEW

**Comment by aszasz** [comment]
Chapter 23 is missing contributors? Should I wait or merge it anyway?

**Comment by aegauthier** [comment]
Let me do that one and let me do the hard stop for all and then we can merge - sounds good?

**Comment by aszasz** [comment]
Yes, sounds good. Thank you.

**Comment by aegauthier** [comment]
@aszasz weirdly Chapter 23 is not in my directory on my computer. Not sure what to do about that.
In the short term, here are the authors
Contributors:
Andre Frieslaar, HHO Africa; Andy Laatz, HHO Africa; Fred de Villiers, HHO Africa; Susan Smit, HHO Africa; Karl Fjellstrom, Far East BRT; Ulises Navarro, ITDP Latin America; Carlos Pardo, Despacio

working on finalizing the other changes and will send soon.

**Comment by aegauthier** [comment]
Hey - so I made the changes (the break between contributors and names) and when i look at the file (click on the pull request bbc420f), i can see the changes but when i look at the live deployment, it doesn't show.  Did I miss a step or something?

**Comment by aszasz** [comment]
I will add the names -- via GitHub interface on your fork (your account, your user space), as you granted me the privilege as an editor.

Chapter 23rd directory is in your computer, it only appears in a more proper name (without a number, but only) "roadway design".

I say its nameing  is better because, if we add or remove chapters (or change the order of the volumes) the name will work better, while the numbering on the guide will automatically change, it will be confusing to find it on the source.

How would you know it? Buy looking at line 69 of [the-guide-src](https://github.com/aegauthier/the-online-brt-planning-guide/blob/authors/guide/the-guide.src).

**Comment by aszasz** [comment]
Just add the names there on Chapter 23rd...
For creating a new paragraph in the source you need to have a blank line. (It is a bit strange at the begining but once you get used to it you realize there are more advantages than inconveniences).

I will tell you to let it as is, for now. I think we will come out with the feature for formating it before TRB, (will discuss that on your feature request #105) 

Still, I wait until you tell me that I can merge this as is. Thank you : )

**Comment by aszasz** [comment]
Reminder @aegauthier: if you choose to keep editing this branch on your computer, you shall (ideally before you begin your edition, but necessarily before you push furhter changes), fetch and merge the change I made into your fork (your remote). For doing that (I assume you have the branch authors checked out): just ``git pull`` on the git bash enviroment.

**Comment by aegauthier** [comment]
Okay - I am not going to do anymore on this. Thanks for the help in finding chapter 23. It is there : ) - one thing about naming it versus numbering it - and i saw this in the chapters too - it is helpful to have the numbers to find what you are looking for unless you are super knowledgeable about what everything is called. I understand your concern, but then there is the navigation issue.

**Comment by aszasz** [comment]
I am showing alternatives without creating the feature ``\author`` (see comments on issue #105)
@aegauthier and @dcpaschall: please check out the different formatting I applied in the first chapters and agree to one, so I can apply it to all chapters, so we don't need to count with the feature for Jan 9th.
1. As is: one liner
3. Splitting line only 
4. Highlight "contributors" word one line
5. Highlight "contributors" and split line
6. one line with emphasis on names
7. one line with emphasis on company (emphasis is made by looking softer)*
8. one line with highlight on "contributors" and emphasis on the company
9. split line with highlight on contributor and emphasis on the company

(Some combinations are missing, because I felt emphasis should be on the company... let me know if want me to do it... my favorite is 8)

[Then I am making this to explore the feature to be created, not for patching before Jan 9th
10. using box]

* Chapter 7 landing page does not have a quote (because it was the overview text), I am not including here because this pull request is about authors... I will send a suggestion in a proper pull request : )

**Comment by aszasz** [comment]
I am merging this, as the authors are there in a reasonable format (I jumped in and chose one to have less stuff to worry during my vacations : ) ... if someone wants to change it again, the new pull request will be "formatting contributors".

**Pull request merged**
