### PR TITLE
CSS: overlay.

### PR DESCRIPTION
**Pull request by craice**
Was #72.

### CODE REVIEW

**Comment by jonasmalacofilho** [comment]
@craice, the two last commits are still about this pr?

**Comment by jonasmalacofilho** [comment]
Got it to work but can't push...  Will see if we get a quick reply from GitHub support, otherwise will open another PR (or merge it directly into master).

**Comment by jonasmalacofilho** [comment]
Actually, this still has some issues:

 - [x] viewport scaling doesn't always scale images respecting aspect ratio (@craice)
- [ ] ~add captions (figures and _img-_tables) (@craice)~

**Comment by craice** [comment]
```
<div class="overlay">
  <img src="...">
</div>
```

```
<div class="overlay">
  <div style="background-image: url(...);"></div>
</div>
```

**Comment by jonasmalacofilho** [comment]
@craice, I implemented the generator part of the overlays and also added blur to the elements under the overlay.

However, I think we should consider the cases that could appear with elements like [Fig. 3.1](https://brtguide.itdp.org/pull_request/90/guide/project-set-up/setup-process.html):
 - images with no border whatsoever (that should indeed be the official guideline)
 - images with transparency

In my mind, having a white background with some small white margin could solve both issues, but I'm not sure.  Also, I couldn't figure out how to test this with the current bg based implementation.

Finally, do you think we should merge as is (after the issues above have been considered) or wait for the captions (and maybe an explicit but discrete close button)? 

---

_I think the close button should be discrete because I believe most people will naturally try to click on anything to close the overlay, if they don't see another obvious and convenient way to do so.  But I could be grossly wrong..._

_Still, since any click makes it to go away and since it's much faster to click anywhere than on some specific button, it might be best to not give too much focus to the "X" button, which could make people think that's the only way to close the overlay._

**Comment by jonasmalacofilho** [comment]
Let's leave the (maybe) missing captions and the issues with transparent images for after #106 has been solved.  Merging as is, already with the open/close hints.

**Pull request merged**
